# Guition ESP32-S3-4848S040 Music Dashboard
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Music"
  room: "Your Room"
  media_player: "media_player.office"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  music_dashboard: github://jtenniswood/esphome-media-player/guition-esp32-s3-4848s040/packages/packages.yaml@main