# ESP32-S3-Touch-LCD-7 Music Dashboard
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Music"
  room: "Your Room"
  media_player: "media_player.office"
  home_assistant_url: "http://homeassistant.local:8123"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-media-player/
    files: [guition-esp32-s3-4848s040/device/device.yaml,
            guition-esp32-s3-4848s040/device/sensors.yaml,
            guition-esp32-s3-4848s040/device/lvgl.yaml,
            guition-esp32-s3-4848s040/addon/backlight.yaml,
            guition-esp32-s3-4848s040/addon/time.yaml,
            guition-esp32-s3-4848s040/addon/network.yaml,
            guition-esp32-s3-4848s040/addon/music.yaml,
            guition-esp32-s3-4848s040/assets/fonts.yaml,
            guition-esp32-s3-4848s040/assets/icons.yaml,
            guition-esp32-s3-4848s040/theme/button.yaml]
    refresh: 1sec
