# Guition ESP32-S3-4848S040 Music Dashboard
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Music"
  room: "Your Room"
  media_player: "media_player.office"
  home_assistant_url: "http://homeassistant.local:8123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  setup:
    url: https://github.com/jtenniswood/esphome-media-player/
    file: guition-esp32-s3-4848s040/guition-esp32-s3-4848s040.yaml
    refresh: 1sec